# Generated by Django 3.1.1 on 2020-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0037_state_all_mail_elections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='all_mail_elections',
            field=models.BooleanField(default=False, verbose_name='Whether state has All Mail Elections'),
        ),
    ]
