# Generated by Django 3.1.1 on 2020-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0038_auto_20200924_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='high_school_student',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='high_school_student',
            field=models.BooleanField(default=False, verbose_name='Can high school students work?'),
        ),
    ]
