# Generated by Django 2.2.6 on 2020-09-14 04:25

from django.db import migrations
import django_enumfield.db.fields
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180911_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age_range',
            field=django_enumfield.db.fields.EnumField(blank=True, default=0, enum=survey.models.AgeRange, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age_range',
            field=django_enumfield.db.fields.EnumField(blank=True, default=0, enum=survey.models.AgeRange, null=True),
        ),
    ]
