# Generated by Django 3.1.1 on 2020-09-14 21:46

from django.db import migrations
import django_enumfield.db.fields
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200914_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age_range',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=survey.models.AgeRange, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age_range',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=survey.models.AgeRange, null=True),
        ),
    ]
